export { BasePage as MobileAppsPage } from '@/shared/components/BasePage';
export { BasePage as AssignmentsPage } from '@/shared/components/BasePage';
export { BasePage as MapRegistrationsPage } from '@/shared/components/BasePage';
export { BasePage as AttendanceListPage } from '@/shared/components/BasePage';
export { BasePage as ScheduleAttendancePage } from '@/shared/components/BasePage';
export { BasePage as EmployeeDataPage } from '@/shared/components/BasePage';
export { BasePage as ReserveVehiclePage } from '@/shared/components/BasePage';
export { BasePage as CanteenPage } from '@/shared/components/BasePage';
export { BasePage as VacationPlanPage } from '@/shared/components/BasePage';
export { BasePage as WeekendWorkPage } from '@/shared/components/BasePage';
export { BasePage as EmployeeRequestsPage } from '@/shared/components/BasePage';
export { BasePage as VacationsPage } from '@/shared/components/BasePage';
export { BasePage as MonthlySummaryPage } from '@/shared/components/BasePage';
export { BasePage as ExamsAndTrainingPage } from '@/shared/components/BasePage';
export { BasePage as SettlementPage } from '@/shared/components/BasePage';
export { BasePage as AbsencePlanPage } from '@/shared/components/BasePage';
export { BasePage as MonthlyAbsencePlanPage } from '@/shared/components/BasePage';
export { BasePage as SchedulePage } from '@/shared/components/BasePage';
export { BasePage as ProjectsActivitiesPage } from '@/shared/components/BasePage';
export { EmployeeReviewPage } from '@/features/employeeReview';
export { EmployeeEvaluationPage } from '@/features/employeeEvaluation';
